// <auto-generated />
namespace DeadSeaCatalogueDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedTranslation_And_RenamedCatNameToTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedTranslation_And_RenamedCatNameToTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201605041900058_AddedTranslation_And_RenamedCatNameToTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
