// <auto-generated />
namespace DeadSeaCatalogueDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_titleEng_and_ingridients_to_Translation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_titleEng_and_ingridients_to_Translation));
        
        string IMigrationMetadata.Id
        {
            get { return "201605062006066_Added_titleEng_and_ingridients_to_Translation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
